# Generated by Django 4.2.4 on 2024-06-10 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_dailygoal_profile"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="monthlygoal",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="weeklygoal",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="yearlygoal",
            unique_together=set(),
        ),
    ]
