# Generated by Django 3.2.1 on 2024-07-08 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0008_dailygoal_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalyticsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_progress', models.FloatField(default=0.0)),
                ('days_left', models.IntegerField(default=0)),
                ('goal_status', models.CharField(default='green', max_length=20)),
                ('performance', models.IntegerField(default=0)),
                ('today_completed', models.BooleanField(default=False)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Analytics Data',
            },
        ),
    ]
