# Generated by Django 3.2.1 on 2024-07-31 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_useranalyticsdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklygoal',
            name='week_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
