# Generated by Django 3.2.1 on 2024-08-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_weeklygoal_week_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklygoal',
            name='week_id',
            field=models.CharField(blank=True, default=None, max_length=30, unique=True),
        ),
    ]
