# Generated by Django 3.2.1 on 2024-08-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_weeklygoal_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearlygoal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
