# Generated by Django 3.2.1 on 2024-08-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_yearlygoal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearlygoal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
