# Generated by Django 3.2.1 on 2024-08-14 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_yearlygoal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedgoal',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.profile'),
        ),
    ]
