# Generated by Django 3.2.1 on 2024-08-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_weeklygoal_week_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklygoal',
            name='week_sequence',
            field=models.IntegerField(default=1),
        ),
    ]
