# Generated by Django 3.2.1 on 2024-08-17 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_weeklygoal_week_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlygoal',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
