# Generated by Django 3.2.1 on 2024-08-22 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_yearlygoal_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranalyticsdata',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.dailygoal'),
        ),
    ]
