# Generated by Django 3.2.1 on 2024-09-08 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0025_auto_20240830_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_number', models.IntegerField()),
                ('month_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_text', models.CharField(max_length=255)),
                ('week_number', models.PositiveIntegerField()),
                ('week_description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='goal',
            name='timeframe_unit',
            field=models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='goal',
            name='timeframe_value',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='goal',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.profile'),
        ),
        migrations.CreateModel(
            name='W',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('week_description', models.TextField()),
                ('goal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.goal')),
                ('month_goal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.m')),
            ],
        ),
        migrations.AddField(
            model_name='m',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.goal'),
        ),
        migrations.CreateModel(
            name='DGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('day_description', models.TextField()),
                ('weekly_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_goals', to='myapp.wgoal')),
            ],
        ),
        migrations.CreateModel(
            name='D1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('day_description', models.TextField()),
                ('goal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.goal')),
                ('week_goal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.w')),
            ],
        ),
    ]
