# Generated by Django 3.2.1 on 2024-09-09 18:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='m',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.profile'),
        ),
        migrations.AddField(
            model_name='m',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
