# Generated by Django 3.2.1 on 2024-09-09 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_auto_20240909_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m',
            name='goal',
        ),
    ]
