# Generated by Django 3.2.1 on 2024-09-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_auto_20240910_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='m',
            name='title',
            field=models.CharField(default='Default Title', max_length=100),
        ),
        migrations.AddField(
            model_name='wgoal',
            name='title',
            field=models.CharField(default='Default Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='d1',
            name='title',
            field=models.CharField(default='Default Title', max_length=100),
        ),
    ]
